items: [
     pepp: [{ title: "Pepp!",
              color: 'url(img/pepp.png)',
              active: false, 
              about: "In this project we explored the possibility to automate the analysis of x-ray images using machine learning and computer vision as a tool for the classification. We did this by creating a scaleable platform for labeling of x-ray images, which is connected with crowdsourcing platforms. The classification of x-ray images of wrists is done using machine learning. The collected data is used to build a library of classified x-ray images which will help to improve the efficiency of analysis of bone fractures.",
              course: "DH1245 Multimodala interaktioner och gränssnitt",
              year: "Fall 2016",
              role: "User Experience",
              tools: "Sketch, JavaScript, Photoshop",
              team: "Emma Klint, Caroline Lönn, Simone Stenis Perron",
              text: [{ headline: "Concept",
                      paragraph: "E-quality ipsum Female software engineers get paid twelve percent less. Female software engineers get paid twelve percent less. After all, one of the founders of computer programming was a woman, Ada Lovelace, back in the 1840s. Women’s acceptance rates dominate over men’s for every programming language in the top 10, to various degrees. It’s just unprofessional. Tech needs to grow up. Twenty percent of female web developers perceive gender bias has hurt them professionally vs one percent of male web developers. Nearly half of all female engineers are leaving the field.",
                      image: 'img/Artboard 5.png'
                    }]
            }],

      { title: "Bilder från en höst",
      	color: 'url(img/Project1.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx"},
      { title: "Axels student",
      	color: 'url(img/Project2.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx"},
      {	title: "Porträttbilder",
      	color: 'url(img/Project3.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx" },
      {	title: "Bokeh och julgranar",
      	color: 'url(img/Project4.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx" },
      {	title: "The end is always near",
      	color: 'url(img/Project5.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx" },
      {	title: "Venndiagram",
      	color: 'url(img/Project6.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx" },
      {	title: "Netlight",
      	color: 'url(img/Project7.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx" },
      {	title: "Material Design",
      	color: 'url(img/Project8.png)',
      	active: false,
      	about: "A project exploring the possibility to automate the analysis of x-rays using machine learning and computer vision as a tool for classification.",
      	course: "DHXXX",
      	year: "2016",
      	role: "xx",
      	tools: "xxx",
      	team: "xxxx" }
    ]